apiVersion: v1
kind: Service
metadata:
  name: overbooking-service
spec:
  type: ClusterIP
  selector:
    app: overbooking-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
