spring.application.name=overbooking-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/overbooking_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

booking-service.url=${BOOKING_SERVICE_URL:http://localhost:8082}
payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8083}

resilience4j.circuitbreaker.instances.paymentClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentClient.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.paymentClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentClient.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentClient.record-exceptions=org.springframework.web.client.ResourceAccessException,org.springframework.web.client.HttpServerErrorException

resilience4j.retry.instances.paymentClient.max-attempts=3
resilience4j.retry.instances.paymentClient.wait-duration=500ms
resilience4j.retry.instances.paymentClient.enable-exponential-backoff=true
resilience4j.retry.instances.paymentClient.exponential-backoff-multiplier=2
resilience4j.retry.instances.paymentClient.enable-randomized-wait=true
resilience4j.retry.instances.paymentClient.randomized-wait-factor=0.5
resilience4j.retry.instances.paymentClient.retry-exceptions=org.springframework.web.client.ResourceAccessException,org.springframework.web.client.HttpServerErrorException

resilience4j.bulkhead.instances.paymentClient.max-concurrent-calls=10
resilience4j.bulkhead.instances.paymentClient.max-wait-duration=0
