apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: ClusterIP
  selector:
    app: customer-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
